# 开发抖音项目使用的配置文件，私密

# mysql 配置
username:   root
password:   123456
host:       127.0.0.1
port:       3306
database:   douyin

# 配置oss对象存储

endpoint:        oss-cn-hangzhou.aliyuncs.com
accessKeyId:     LTAI5tHoVrRqxpd7pFXKHjq7
accessKeySecret: 5t7EpZ5rebkXLzs3dbmsaHT72kcGL6
examplebucket:   oss-douyin-video-cover-content #存储桶




