# 配置文件模板
# 配置oss基本信息
# 建议复制该模板到同一文件夹下并改名为 config.yaml，然后在上面填写相关信息，这样你提交github的时候可以使用gitignore保护个人信息。
# 当然也可以将信息填写到该文件上，并将文件名改名为 config.yaml 因为代码读入的文件名为该文件夹下的config.yaml



# mysql 配置，按需修改，记得改密码
username:   root
password:   
host:         127.0.0.1
port:       3306
database:   douyin

# 配置oss对象存储, 可以去oss控制台查看相关配置，Examplebucket为存储桶的名字

endpoint:        
accessKeyId:     
accessKeySecret: 
examplebucket:   oss-douyin-video-cover-content

